pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'I am building'
            }
        }
          stage('Test') {
            steps {
                echo 'I am testing again'
            }
        }
        stage('double test') {
            steps {
                echo 'I am testing again and again'
            }
        }
        stage('Deploy') {
            steps {
                echo 'I am deploying exactly'
            }
        }
        stage('Deploy again') {
            steps {
                echo 'i am at last!!!!!!!!!!!'
            }
        }
    }
}
