pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'I am building'
            }
        }
        stage('double test') {
            steps {
                echo 'I am testing again'
            }
        }
        stage('Deploy') {
            steps {
                echo 'I am deploying'
            }
        }
        stage('Deploy again') {
            steps {
                echo 'i am at last!!!!!!!!!!!'
            }
        }
    }
}
